### ISSUE TITLE
AttributeError: 'Gpib' object has no attribute 'close'

### ISSUE THREAD

**Issue by Irv1n** [PatrickBaus/pyAsyncGpib#1]
Hi! At first thank you for this scripts!
When I try to run example i have an error: AttributeError: 'Gpib' object has no attribute 'close'. I use linux-gpib driver with my devices.

**Comment by PatrickBaus** [comment]
Hello Irv1n,
can you be a little more specific? Can you post the full Traceback? Wich version of linux gpib are you using? Which GPIB adapter?

**Comment by Irv1n** [comment]
`DEBUG:asyncio:Using selector: EpollSelector
Controller version: 4.3.3
Traceback (most recent call last):
  File "/home/vadim/examples/example.py", line 42, in <module>
    asyncio.run(main())
  File "/home/vadim/.pyenv/versions/3.9.4/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/vadim/.pyenv/versions/3.9.4/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/vadim/examples/example.py", line 39, in main
    await gpib_device.disconnect()
  File "../pyAsyncGpib/AsyncGpib.py", line 53, in disconnect
    await self.close()
  File "../pyAsyncGpib/AsyncGpib.py", line 69, in close
    await self.__wrapper(self.__device.close)
AttributeError: 'Gpib' object has no attribute 'close'
`
I use GPIB-USB-HS adapter
LINUX_GPIB_VER="4.3.3"

**Comment by PatrickBaus** [comment]
Well, this is weird. I just checked against my setup, which mostly the same. I do run Python 3.8.5 though, but does not make a difference here. Did you install linux gpib from the source or did you use some kind of package?

You can try to check whether the method in question is indeed missing in your library (if not built from source).
run python from the console using
`python -v`
then type
`import Gpib`
This lists the path of the module like
/usr/local/lib/python3.8/dist-packages/
open the Gpib.py file an check for the close() method. It should be there.

**Comment by Irv1n** [comment]
hmm interest I done have close method in Gpib.py
I reinstall package and now have close method and all is work fine. Thank you!

**Comment by PatrickBaus** [comment]
Great to hear and closing.
